"""empty message

Revision ID: 7b8d5011742e
Revises: df80fd943985
Create Date: 2021-08-17 23:22:51.328215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b8d5011742e'
down_revision = 'df80fd943985'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detalleordentrabajo', sa.Column('id_ordentrabajo', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'detalleordentrabajo', 'ordentrabajo', ['id_ordentrabajo'], ['id'])
    op.add_column('ordentrabajo', sa.Column('id_contrato', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'ordentrabajo', 'contrato', ['id_contrato'], ['id'])
    op.add_column('statusorden', sa.Column('id_contrato', sa.Integer(), nullable=True))
    op.add_column('statusorden', sa.Column('id_userorden', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'statusorden', 'userorden', ['id_userorden'], ['id'])
    op.create_foreign_key(None, 'statusorden', 'contrato', ['id_contrato'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'statusorden', type_='foreignkey')
    op.drop_constraint(None, 'statusorden', type_='foreignkey')
    op.drop_column('statusorden', 'id_userorden')
    op.drop_column('statusorden', 'id_contrato')
    op.drop_constraint(None, 'ordentrabajo', type_='foreignkey')
    op.drop_column('ordentrabajo', 'id_contrato')
    op.drop_constraint(None, 'detalleordentrabajo', type_='foreignkey')
    op.drop_column('detalleordentrabajo', 'id_ordentrabajo')
    # ### end Alembic commands ###
