"""empty message

Revision ID: b9e96bc41fdb
Revises: 570d9bf47591
Create Date: 2021-08-17 23:31:03.550544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9e96bc41fdb'
down_revision = '570d9bf47591'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('statusorden', 'final_fecha',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('statusorden', 'inicio_fecha',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('statusorden', 'inicio_fecha',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('statusorden', 'final_fecha',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###
