"""empty message

Revision ID: c16c79a77092
Revises: 341972ef4cf4
Create Date: 2021-08-17 22:35:41.672417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c16c79a77092'
down_revision = '341972ef4cf4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userorden', sa.Column('id_orden', sa.Integer(), nullable=True))
    op.add_column('userorden', sa.Column('id_user', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'userorden', 'ordentrabajo', ['id_orden'], ['id'])
    op.create_foreign_key(None, 'userorden', 'user', ['id_user'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'userorden', type_='foreignkey')
    op.drop_constraint(None, 'userorden', type_='foreignkey')
    op.drop_column('userorden', 'id_user')
    op.drop_column('userorden', 'id_orden')
    # ### end Alembic commands ###
