"""empty message

Revision ID: d0f3b6c96c0d
Revises: 341972ef4cf4
Create Date: 2021-08-19 11:15:03.653130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0f3b6c96c0d'
down_revision = '341972ef4cf4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tipoordentrabajo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=False),
    sa.Column('id_ordentrabajo', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_ordentrabajo'], ['ordentrabajo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('detalleordentrabajo')
    op.drop_table('userorden')
    op.add_column('acreditacion', sa.Column('id_ordentrabajo', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'acreditacion', 'ordentrabajo', ['id_ordentrabajo'], ['id'])
    op.add_column('contrato', sa.Column('id_user', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'contrato', 'user', ['id_user'], ['id'])
    op.add_column('ordentrabajo', sa.Column('id_contrato', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'ordentrabajo', 'contrato', ['id_contrato'], ['id'])
    op.add_column('statusorden', sa.Column('geo_lat', sa.String(length=120), nullable=False))
    op.add_column('statusorden', sa.Column('geo_lon', sa.String(length=120), nullable=False))
    op.add_column('statusorden', sa.Column('id_contrato', sa.Integer(), nullable=True))
    op.add_column('statusorden', sa.Column('id_ordentrabajo', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'statusorden', 'contrato', ['id_contrato'], ['id'])
    op.create_foreign_key(None, 'statusorden', 'ordentrabajo', ['id_ordentrabajo'], ['id'])
    op.drop_column('statusorden', 'geo_longitud')
    op.drop_column('statusorden', 'geo_latitud')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('statusorden', sa.Column('geo_latitud', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.add_column('statusorden', sa.Column('geo_longitud', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'statusorden', type_='foreignkey')
    op.drop_constraint(None, 'statusorden', type_='foreignkey')
    op.drop_column('statusorden', 'id_ordentrabajo')
    op.drop_column('statusorden', 'id_contrato')
    op.drop_column('statusorden', 'geo_lon')
    op.drop_column('statusorden', 'geo_lat')
    op.drop_constraint(None, 'ordentrabajo', type_='foreignkey')
    op.drop_column('ordentrabajo', 'id_contrato')
    op.drop_constraint(None, 'contrato', type_='foreignkey')
    op.drop_column('contrato', 'id_user')
    op.drop_constraint(None, 'acreditacion', type_='foreignkey')
    op.drop_column('acreditacion', 'id_ordentrabajo')
    op.create_table('userorden',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name='userorden_pkey')
    )
    op.create_table('detalleordentrabajo',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tipo', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('descripcion', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='detalleordentrabajo_pkey')
    )
    op.drop_table('tipoordentrabajo')
    # ### end Alembic commands ###
