"""empty message

Revision ID: df80fd943985
Revises: c16c79a77092
Create Date: 2021-08-17 22:46:39.179948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df80fd943985'
down_revision = 'c16c79a77092'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('acreditacion', sa.Column('id_userorden', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'acreditacion', 'userorden', ['id_userorden'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'acreditacion', type_='foreignkey')
    op.drop_column('acreditacion', 'id_userorden')
    # ### end Alembic commands ###
